/**
 * Created by 23rd and Walnut
 * www.23andwalnut.com
 * User: Saleem El-Amin
 * Date: 6/8/11
 * Time: 9:39 AM
 */

var myPlaylist = [

    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Artist',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'http://images.bol.de/images-adb/79/66/7966a83c-22bf-4c5c-83cd-17ef7b264d9a.jpg'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    },
    {
        mp3:'http://blackout.lgnas.com/1.mp3',
        oga:'/site-media/demo/mix/1.ogg',
        title:'Sample',
        artist:'Sample',
        album:'Album',
        rating:4,
        buy:'#',
        price:'0.99',
        duration:'0:30',
        cover:'/site-media/demo/mix/1.png'
    }
];
