application: music-wall
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: latest

handlers:
- url: /docs
  static_dir: docs

- url: /site-media
  static_dir: site-media

- url: .*
  script: main.app

